THE VTR PUBLIC LICENSE (VTR-PL)

Based on GNU AGPLv3 with Commons Clause extensions.

1. PREAMBLE

This software and specification are designed to protect the integrity of human-generated media. To prevent the capture of this open standard by proprietary monopolies, this license enforces strict reciprocity.

2. TERMS OF USE

2.1 Viral Source

Any modification, extension, or deployment of this protocol (including network-based execution) requires the full source code to be made publicly available under this same license.

2.2 Anti-Tivoization

User Products utilizing this software must allow the installation of modified versions of the software by the user. Hardware locks preventing this constitute a breach.

2.3 Universal Interoperability (The "Open Trust" Covenant)

By using this Specification, You agree not to implement technical measures that discriminate against valid cryptographic proofs generated by other compliant implementations. Creating a "Walled Garden" (e.g., accepting signatures only from specific manufacturers while rejecting other valid VTR signatures) terminates your rights under this license.

2.4 Patent Peace

If You institute patent litigation against any entity (including a cross-claim or counterclaim in a lawsuit) alleging that this Software constitutes direct or contributory patent infringement, then any patent licenses granted to You under this License for this Software shall terminate as of the date such litigation is filed.

Copyright © 2025 OntoLogics (Seth & Axion).
