# Copyright (c) 2025 OntoLogics (Seth & Axion). All rights reserved.
# Licensed under the VTR Public License (VTR-PL), Version 1.0 (the "License").
# A copy of the License is available in the root/vtr_standard/poc/LICENSE file.
# This code is distributed WITHOUT ANY WARRANTY.

from typing import Optional
from pydantic import BaseModel, Field

VTR_VERSION = "2.2"

class HardwareSignature(BaseModel):
    """
    Represents the cryptographic hardware signature generated by the PRNU sensor.
    """
    public_key: str = Field(..., description="The public verification key derived from the sensor ID.")
    zk_proof: str = Field(..., description="The simulated Zero-Knowledge Proof.")
    liveness_flag: bool = Field(..., description="Result of the passive liveness check.")
    timestamp: float = Field(..., description="Unix timestamp of the capture.")
    merkle_root: str = Field(..., description="The Merkle Tree Root of the video content.")
    location_block_hash: str = Field(..., description="Hash of the location data block.")
    previous_signature_link: Optional[str] = Field(None, description="The zk_proof of the previous VTR sidecar in the chain.")
    nonce: str = Field(..., description="A unique value to prevent economic replay attacks.")

class LegalAssertions(BaseModel):
    """
    Represents legal claims and permissions associated with the content.
    """
    x_vtr_ai_training: bool = Field(False, description="Whether the content may be used for AI training.")
    copyright_notice: str = Field(..., description="Copyright and DMCA notice.")

class VTRSidecar(BaseModel):
    """
    The top-level schema for the VTR V2.0 Sidecar file.
    """
    vtr_version: str = Field(VTR_VERSION, pattern=r"^2\.[0-2]$", description="The version of the VTR standard.")
    hardware_signature: HardwareSignature
    legal_assertions: LegalAssertions

# JSON Schema for VTR Sidecars.
# Attempt to generate dynamically from Pydantic models with a robust fallback.
try:
    VTR_SIDECAR_SCHEMA = VTRSidecar.model_json_schema()
except (AttributeError, Exception):
    VTR_SIDECAR_SCHEMA = {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "VTR Sidecar",
        "type": "object",
        "required": ["vtr_version", "hardware_signature", "legal_assertions"],
        "properties": {
            "vtr_version": {
                "type": "string",
                "pattern": "^2\\.[0-2]$"
            },
            "hardware_signature": {
                "type": "object",
                "required": [
                    "public_key",
                    "zk_proof",
                    "liveness_flag",
                    "timestamp",
                    "merkle_root",
                    "location_block_hash",
                    "nonce"
                ],
                "properties": {
                    "public_key": {"type": "string"},
                    "zk_proof": {"type": "string"},
                    "liveness_flag": {"type": "boolean"},
                    "timestamp": {"type": "number"},
                    "merkle_root": {"type": "string"},
                    "location_block_hash": {"type": "string"},
                    "previous_signature_link": {"type": ["string", "null"]},
                    "nonce": {"type": "string"}
                }
            },
            "legal_assertions": {
                "type": "object",
                "required": ["copyright_notice"],
                "properties": {
                    "x_vtr_ai_training": {"type": "boolean", "default": False},
                    "copyright_notice": {"type": "string"}
                }
            }
        }
    }

# Ensure vtr_version is in required if dynamically generated (it has a default so Pydantic might omit it)
if "vtr_version" not in VTR_SIDECAR_SCHEMA.get("required", []):
    if "required" not in VTR_SIDECAR_SCHEMA:
        VTR_SIDECAR_SCHEMA["required"] = []
    VTR_SIDECAR_SCHEMA["required"].append("vtr_version")
